// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VizsgaremekApp.Models;

#nullable disable

namespace tempbackend.Migrations
{
    [DbContext(typeof(VizsgaremekContext))]
    partial class VizsgaremekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tempbackend.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("VizsgaremekApp.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIdo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ValasztottCsomagId")
                        .HasColumnType("int");

                    b.Property<int>("ValasztottOktatoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VizsgaremekApp.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nagy Gergely"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kovács Ákos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tőth László"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Szabó Tamás"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horváth Márton"
                        });
                });

            modelBuilder.Entity("VizsgaremekApp.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Különleges Alakulat",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orosz",
                            Price = 25500m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Magyar",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "9mm-es pisztoly",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "9mm-es géppisztoly",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "5.56 NATO és .300 blackout",
                            Price = 75000m
                        },
                        new
                        {
                            Id = 7,
                            Name = "7.62-es",
                            Price = 45000m
                        });
                });

            modelBuilder.Entity("VizsgaremekApp.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Minosites")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MinositesIdeje")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
